services:
    Wakeapp\Bundle\ApiPlatformBundle\EventListener\ApiControllerArgumentListener:
        class:      Wakeapp\Bundle\ApiPlatformBundle\EventListener\ApiControllerArgumentListener
        arguments:
            - '@linkin_swagger_resolver.factory'
        tags:
            - { name: kernel.event_listener, event: kernel.controller_arguments }

    Wakeapp\Bundle\ApiPlatformBundle\EventListener\ApiResponseListener:
        class:      Wakeapp\Bundle\ApiPlatformBundle\EventListener\ApiResponseListener
        arguments:
            - '@wakeapp_api_platform.guesser.api_error_code'
            - '@wakeapp_api_platform.factory.api_dto'
            - '@Wakeapp\Bundle\ApiPlatformBundle\Logger\ApiPlatformLogger'
            - '@translator'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 1 }
            - { name: kernel.event_listener, event: kernel.response }

    Wakeapp\Bundle\ApiPlatformBundle\Factory\ApiDtoFactory:
        class:      Wakeapp\Bundle\ApiPlatformBundle\Factory\ApiDtoFactory
        arguments:
            - '@linkin_swagger_resolver.factory'
    wakeapp_api_platform.factory.api_dto:
        alias:      Wakeapp\Bundle\ApiPlatformBundle\Factory\ApiDtoFactory

    Wakeapp\Bundle\ApiPlatformBundle\Logger\ApiPlatformLogger:
        calls:
            - ['setLogger', ['@?logger']]
        tags:
            - { name: 'monolog.logger', channel: 'api_platform' }
