services:
    MarfaTech\Bundle\ApiPlatformBundle\ArgumentResolver\ApiCollectionEntryDtoArgumentResolver:
        arguments:
            - '@marfa_tech_api_platform.factory.api_dto'
        calls:
            - [ 'setLogger', [ '@MarfaTech\Bundle\ApiPlatformBundle\Logger\ApiPlatformLogger' ] ]
        tags:
            - { name: controller.argument_value_resolver, priority: 250 }

    MarfaTech\Bundle\ApiPlatformBundle\ArgumentResolver\ApiEntryDtoArgumentResolver:
        arguments:
            - '@marfa_tech_api_platform.factory.api_dto'
        calls:
            - [ 'setLogger', [ '@MarfaTech\Bundle\ApiPlatformBundle\Logger\ApiPlatformLogger' ] ]
        tags:
            - { name: controller.argument_value_resolver, priority: 250 }

    MarfaTech\Bundle\ApiPlatformBundle\EventListener\ApiResponseListener:
        class:      MarfaTech\Bundle\ApiPlatformBundle\EventListener\ApiResponseListener
        arguments:
            - '@marfa_tech_api_platform.guesser.api_error_code'
            - '@marfa_tech_api_platform.factory.api_dto'
            - '@?translator'
        calls:
            - ['setLogger', ['@MarfaTech\Bundle\ApiPlatformBundle\Logger\ApiPlatformLogger']]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 1 }
            - { name: kernel.event_listener, event: kernel.response }

    MarfaTech\Bundle\ApiPlatformBundle\EventListener\MinimalApiVersionRequestListener:
        arguments:
            - '%marfa_tech_api_platform.minimal_api_version%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 128 }

    MarfaTech\Bundle\ApiPlatformBundle\Factory\ApiDtoResolverFactoryInterface: '@marfa_tech_api_platform.factory.api_dto'

    MarfaTech\Bundle\ApiPlatformBundle\Logger\ApiPlatformLogger:
        arguments:
            - '@?logger'
        tags:
            - { name: 'monolog.logger', channel: 'marfa_tech_api_platform' }

    MarfaTech\Bundle\ApiPlatformBundle\Factory\ApiDtoResolverFactory:
        class:      MarfaTech\Bundle\ApiPlatformBundle\Factory\ApiDtoResolverFactory
        arguments:
            - '@MarfaTech\Bundle\ApiPlatformBundle\Factory\ResolverFactoryInterface'
