name: PHPUnit

on: [pull_request]

jobs:
  run:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php: ['8.0', '8.1']
        symfony: ['~4.4', '~5.4', '~6.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
        env:
          COMPOSER_TOKEN: ${{ secrets.COMPOSER_TOKEN }}

      - name: Export Symfony version ${{ matrix.symfony }}
        run: export SYMFONY_REQUIRE=${{ matrix.symfony }}

      - name: Composer update on php ${{ matrix.php }} and symfony ${{ matrix.symfony }}
        run: SYMFONY_REQUIRE=${{ matrix.symfony }} composer update --prefer-dist --no-progress

      - name: Run tests
        run: |
          ./vendor/bin/phpunit

