name: PHPUnit

on: [pull_request]

jobs:
  run:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
#        php-versions: ['8.0', '8.1']
#        symfony-versions: ['~4.4', '~5.4', '~6.0']
        php-versions: [ '8.0' ]
        symfony-versions: [ '~4.4' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer
        env:
          COMPOSER_TOKEN: ${{ secrets.COMPOSER_TOKEN }}

      - name: Configure symfony/flex
        run: composer config --no-plugins allow-plugins.symfony/flex true

      - name: Configure symfony extra
        run: composer config extra.symfony.require "${{ matrix.symfony-version }}"

#      - name: Export Symfony version ${{ matrix.symfony-versions }}
#        run: export SYMFONY_REQUIRE=${{ matrix.symfony-versions }}

      - name: Composer install on php ${{ matrix.php-versions }} and symfony ${{ matrix.symfony-versions }}
        run: composer install --prefer-dist --no-progress

      - name: Run tests
        run: |
          ./vendor/bin/phpunit

